DROP USER IF EXISTS 'user1'@'%';
DROP USER IF EXISTS 'user1'@'localhost';
CREATE USER 'user1'@'%' IDENTIFIED BY 'PASSWORD';
GRANT USAGE ON *.* TO 'user1'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'user1'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
